[package]
name = "rust-wgpu-breakout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "core",
    "render",
]

[dependencies]
pretty_env_logger = "0.4.0"
log = "0.4.14"
glam = "0.20.1"
core = { path = "./core" }

[[example]]
name = "pong"

[[example]]
name = "breakout"