[package]
name = "rust-wgpu-breakout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "core",
    "render",
    "shapes",
]

[dependencies]
pretty_env_logger = "0.4.0"
log = "0.4.14"
glam = "0.20.1"
core = { path = "./core" }
shapes = { path = "./shapes" }
physics2d = { path = "./physics2d" }
hecs = "0.7.1"
rand = "0.8.4"

[[example]]
name = "pong"

[[example]]
name = "breakout"