[package]
name = "breakout_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "render",
    "shapes",
]

[dependencies]
pretty_env_logger = "0.4.0"
log = "0.4.14"
glam = "0.20.1"
shapes = { path = "./shapes" }
physics2d = { path = "./physics2d" }
hecs = "0.7.1"
rand = "0.8.4"
anyhow = "1.0"
pollster = "0.2"
winit = "0.26.0"
image = "0.23"
render = { path = "./render", default-features = false, features = ["opengl"] }


[[example]]
name = "pong"
[[example]]
name = "snake"
[[example]]
name = "empty"

[profile.dev_shader]
inherits = "dev"