[package]
name = "rust-wgpu-breakout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.25"
cgmath = "0.18"
nalgebra = "0.29.0"
glam = "0.20.1"
env_logger = "0.9"
log = "0.4"
wgpu = { version = "0.11.0", features = [ "spirv" ] }
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
anyhow = "1.0"
shaderc = "0.7.3"